name: Dockerfile PR checks

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for Dockerfile changes 
      run: |
        changed_files="$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})"
        echo $changed_files
        if echo $changed_files | grep -qE 'Dockerfile'; then
          echo "Dockerfile changed, running checks"
          exit 0
        else
          echo "No Dockerfile changes, skipping checks"
          exit 1
        fi

    - name: Install hadolint
      run: |
        curl -sSL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64"
        chmod +x hadolint
        sudo mv hadolint /usr/local/bin/

    - name: Run hadolint
      run: hadolint Dockerfile

    - name: Build Docker container
      run: docker build -t my-container .
